version: '3'

services:
  livraria_database:
    image: mysql:5.7
    restart: always
    expose:
      - 3306
    env_file:
      - livraria_database.env
      
  livraria_app:
    image: alura/livraria-api
    restart: always
    ports:
      - 8180:8180
    depends_on:
      - livraria_database
    env_file:
      - livraria_app.env